version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - '${DATABASE_PORT}:5432'
