version: '3.8'

services:
  db:
    image: postgres
    container_name: user-postgres-container
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-microservice-container
    ports:
      - "8080:8080"
    depends_on:
      - db